name: CI (Integração continua) Main Worflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: yarn install
      - name: Run preview deployment
        run: yarn deploy:preview
